from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func
from typing import List
from datetime import datetime
from pydantic import BaseModel

from ...core.database import get_db
from ...models.models import Member, AttendanceLog, Team
from ...services.qr_service import decrypt_qr_data

router = APIRouter()

class ScanRequest(BaseModel):
    encrypted_data: str
    scanned_by: str = "scanner"
    encryption_password: str = None

class ScanResponse(BaseModel):
    success: bool
    message: str
    member_data: dict = None
    already_checked_in: bool = False

@router.post("/scan", response_model=ScanResponse)
async def scan_qr(request: ScanRequest, db: Session = Depends(get_db)):
    """Scan QR code and mark attendance"""
    
    try:
        # Decrypt QR data
        try:
            data = decrypt_qr_data(request.encrypted_data, encryption_password=request.encryption_password)
        except Exception as decrypt_error:
            raise HTTPException(
                status_code=400, 
                detail=f"Failed to decrypt QR code. Make sure you're scanning a valid QR code generated by this system. Error: {str(decrypt_error)}"
            )
        
        member_id = data.get('member_id')
        
        if not member_id:
            raise HTTPException(
                status_code=400, 
                detail=f"Invalid QR code: member_id not found in data. QR contains: {list(data.keys())}"
            )
        
        # Get member
        member = db.query(Member).filter(Member.id == member_id).first()
        if not member:
            raise HTTPException(
                status_code=404, 
                detail=f"Member with ID {member_id} not found in database"
            )
        
        # Check if already checked in
        if member.is_checked_in:
            return ScanResponse(
                success=True,
                message=f"{member.name} is already checked in",
                member_data=data,
                already_checked_in=True
            )
        
        # Mark as checked in
        member.is_checked_in = True
        member.checked_in_at = datetime.utcnow()
        
        # Create attendance log
        log = AttendanceLog(
            member_id=member.id,
            action="check_in",
            scanned_by=request.scanned_by
        )
        db.add(log)
        db.commit()
        
        return ScanResponse(
            success=True,
            message=f"Welcome {member.name}! Check-in successful",
            member_data=data,
            already_checked_in=False
        )
        
    except HTTPException:
        raise
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=400, detail=f"Scan failed: {str(e)}")

@router.get("/attendance/{event_id}")
async def get_attendance(event_id: int, db: Session = Depends(get_db)):
    """Get attendance statistics for event"""
    
    # Get total members
    total_members = db.query(Member).join(Team).filter(Team.event_id == event_id).count()
    
    # Get checked in members
    checked_in = db.query(Member).join(Team).filter(
        Team.event_id == event_id,
        Member.is_checked_in == True
    ).count()
    
    # Get recent check-ins
    recent_logs = db.query(AttendanceLog).join(Member).join(Team).filter(
        Team.event_id == event_id
    ).order_by(AttendanceLog.timestamp.desc()).limit(10).all()
    
    recent_check_ins = []
    for log in recent_logs:
        recent_check_ins.append({
            "member_name": log.member.name,
            "team_name": log.member.team.team_name,
            "timestamp": log.timestamp.isoformat(),
            "action": log.action
        })
    
    return {
        "total_members": total_members,
        "checked_in": checked_in,
        "pending": total_members - checked_in,
        "attendance_rate": round((checked_in / total_members * 100) if total_members > 0 else 0, 2),
        "recent_check_ins": recent_check_ins
    }

@router.get("/logs/{event_id}")
async def get_attendance_logs(
    event_id: int,
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db)
):
    """Get all attendance logs for event"""
    
    logs = db.query(AttendanceLog).join(Member).join(Team).filter(
        Team.event_id == event_id
    ).order_by(AttendanceLog.timestamp.desc()).offset(skip).limit(limit).all()
    
    result = []
    for log in logs:
        result.append({
            "id": log.id,
            "member_id": log.member_id,
            "member_name": log.member.name,
            "team_name": log.member.team.team_name,
            "action": log.action,
            "timestamp": log.timestamp.isoformat(),
            "scanned_by": log.scanned_by
        })
    
    return result

@router.post("/verify-qr")
async def verify_qr(request: ScanRequest):
    """Verify if QR code data is valid (for testing)"""
    try:
        data = decrypt_qr_data(request.encrypted_data, encryption_password=request.encryption_password)
        return {
            "valid": True,
            "data": data,
            "message": "QR code is valid and can be decrypted"
        }
    except Exception as e:
        return {
            "valid": False,
            "error": str(e),
            "message": "QR code is invalid or cannot be decrypted"
        }
